// import {mockData} from './mockdata.js';

/* global db print */
/* eslint no-restricted-globals: "off" */


////https://www.generatedata.com/

const mockData = [
	{
		"name": "Bruno Lester",
		"contactFrequency": "Biannual",
		"email": "lacinia@luctus.com",
		"phone": "1-190-889-6225",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "eu,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Lectus Rutrum Limited",
		"title": "elementum sem, vitae",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Hedda Alexander",
		"contactFrequency": "Yearly",
		"email": "non@cursus.com",
		"phone": "1-680-523-6606",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "nibh",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Aliquet Company",
		"title": "dictum magna.",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Slade Q. Rivera",
		"contactFrequency": "Quarterly",
		"email": "enim@auctorvitaealiquet.org",
		"phone": "1-108-866-9079",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "intimate",
		"contextSpace": "dictum.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Quam Quis Company",
		"title": "rutrum lorem ac",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Kaden Taylor",
		"contactFrequency": "Yearly",
		"email": "nec.euismod.in@dignissim.org",
		"phone": "1-177-311-8863",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "risus.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Luctus Industries",
		"title": "eget magna. Suspendisse",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Paul Q. Dalton",
		"contactFrequency": "Biweekly",
		"email": "placerat.augue.Sed@Vestibulumaccumsanneque.com",
		"phone": "1-798-917-1652",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "eleifend",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Gravida Molestie Ltd",
		"title": "enim nec tempus",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Hayden Orr",
		"contactFrequency": "Biweekly",
		"email": "Suspendisse.ac.metus@Donec.co.uk",
		"phone": "1-987-546-0696",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "ridiculus",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Montes Nascetur Ridiculus Company",
		"title": "faucibus orci",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Kaden Whitley",
		"contactFrequency": "Monthly",
		"email": "magnis@amet.org",
		"phone": "1-672-346-8200",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "commodo",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Tortor Company",
		"title": "egestas",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Alfonso G. Farrell",
		"contactFrequency": "Weekly",
		"email": "neque@maurisut.net",
		"phone": "1-384-293-6590",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "intimate",
		"contextSpace": "aliquam,",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Sem Consulting",
		"title": "felis eget varius",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Chandler V. Clayton",
		"contactFrequency": "Yearly",
		"email": "neque.et@tellusnon.org",
		"phone": "1-719-267-9589",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "Nunc",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Gravida Praesent Associates",
		"title": "vel, mauris. Integer",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Hollee K. Gomez",
		"contactFrequency": "Quarterly",
		"email": "at.pede@Namacnulla.ca",
		"phone": "1-939-209-0780",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "egestas",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Quam Vel Sapien Corporation",
		"title": "metus",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Drew T. Green",
		"contactFrequency": "Weekly",
		"email": "faucibus@ridiculusmus.org",
		"phone": "1-550-281-7185",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "tortor.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Sed Nunc Industries",
		"title": "massa non",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Zane D. Melton",
		"contactFrequency": "Biweekly",
		"email": "venenatis.vel@nisidictumaugue.com",
		"phone": "1-800-516-5495",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "porttitor",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Diam Associates",
		"title": "Nunc",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Dorian Mcmillan",
		"contactFrequency": "Monthly",
		"email": "rutrum.urna@pede.ca",
		"phone": "1-753-346-3202",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "est",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Praesent LLP",
		"title": "lobortis augue scelerisque",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Leroy D. Suarez",
		"contactFrequency": "Biweekly",
		"email": "lobortis.risus.In@ornare.net",
		"phone": "1-325-539-2223",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "mi",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Rhoncus Id Foundation",
		"title": "est mauris, rhoncus",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Noelle W. Holmes",
		"contactFrequency": "Yearly",
		"email": "habitant.morbi@variuseteuismod.com",
		"phone": "1-167-205-9185",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "non,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut",
		"company": "Integer Tincidunt Company",
		"title": "pede blandit",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Imelda Frost",
		"contactFrequency": "Biweekly",
		"email": "enim.nisl.elementum@pellentesquetellussem.edu",
		"phone": "1-764-854-9397",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "Donec",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut",
		"company": "Consequat Enim Diam Incorporated",
		"title": "luctus et",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Aladdin Mays",
		"contactFrequency": "Monthly",
		"email": "lectus@convallis.net",
		"phone": "1-896-734-6798",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "nulla",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Consectetuer Adipiscing Ltd",
		"title": "dictum",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Alden R. Miles",
		"contactFrequency": "Quarterly",
		"email": "leo.Cras@commodoauctor.org",
		"phone": "1-149-531-9017",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "molestie",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Eu Tempor Erat Corporation",
		"title": "erat. Sed nunc",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "John Jacobson",
		"contactFrequency": "Biweekly",
		"email": "Nullam.lobortis.quam@ullamcorperDuis.co.uk",
		"phone": "1-952-446-7561",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "Cras",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Euismod Est Foundation",
		"title": "diam.",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Lunea Richards",
		"contactFrequency": "Weekly",
		"email": "consequat.enim.diam@quamvel.com",
		"phone": "1-830-193-7449",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "lacinia",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Lorem Ipsum PC",
		"title": "aliquet",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Olga Rios",
		"contactFrequency": "Monthly",
		"email": "erat.vel.pede@Sed.net",
		"phone": "1-154-925-7272",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "auctor",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Eget Ipsum Corporation",
		"title": "risus.",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Mark O. Zimmerman",
		"contactFrequency": "Monthly",
		"email": "semper@sit.edu",
		"phone": "1-658-497-3799",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "neque.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Pharetra Nibh Aliquam LLC",
		"title": "Aliquam rutrum",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Arden Z. Porter",
		"contactFrequency": "Yearly",
		"email": "varius.orci.in@Pellentesqueultriciesdignissim.ca",
		"phone": "1-936-118-3099",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "pede",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Turpis Egestas Fusce Corporation",
		"title": "mauris elit, dictum",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Cairo Barker",
		"contactFrequency": "Biweekly",
		"email": "eu@iaculisaliquet.co.uk",
		"phone": "1-697-147-6786",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "Donec",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut",
		"company": "Nulla At Institute",
		"title": "purus,",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Fallon M. Mckay",
		"contactFrequency": "Weekly",
		"email": "Fusce.mi@pedeCum.net",
		"phone": "1-665-276-9528",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "faucibus",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Convallis Est LLC",
		"title": "Integer",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Liberty H. Molina",
		"contactFrequency": "Biweekly",
		"email": "risus.at.fringilla@liberoDonec.org",
		"phone": "1-467-590-3561",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "vehicula",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Libero Corp.",
		"title": "quam.",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Gretchen Q. Smith",
		"contactFrequency": "Weekly",
		"email": "eu@hendrerit.edu",
		"phone": "1-120-839-5147",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "mollis",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Mauris Ipsum Company",
		"title": "et",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Leandra Reyes",
		"contactFrequency": "Monthly",
		"email": "nunc@sed.ca",
		"phone": "1-768-581-7522",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "amet",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Curabitur Massa Incorporated",
		"title": "enim.",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Ora I. Huffman",
		"contactFrequency": "Quarterly",
		"email": "nec@dictum.net",
		"phone": "1-610-149-8136",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "tortor.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Placerat LLP",
		"title": "id, libero. Donec",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Lois F. Bauer",
		"contactFrequency": "Quarterly",
		"email": "dolor@turpis.net",
		"phone": "1-360-119-5088",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "commodo",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Auctor Velit Aliquam LLC",
		"title": "vitae,",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Salvador X. Petty",
		"contactFrequency": "Monthly",
		"email": "est.congue.a@ultricesVivamus.org",
		"phone": "1-317-106-1582",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "magna",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Vivamus Rhoncus Inc.",
		"title": "eget ipsum. Suspendisse",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Plato Rodriquez",
		"contactFrequency": "Quarterly",
		"email": "nibh.Quisque.nonummy@diam.com",
		"phone": "1-438-258-0556",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "Cum",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Diam Nunc Ullamcorper Incorporated",
		"title": "non enim. Mauris",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Nathaniel A. Lester",
		"contactFrequency": "Yearly",
		"email": "risus.Donec@nisl.edu",
		"phone": "1-228-658-7627",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "mi.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Augue Porttitor Company",
		"title": "ridiculus mus.",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Murphy Y. Tillman",
		"contactFrequency": "Monthly",
		"email": "Etiam.imperdiet@Quisquenonummyipsum.com",
		"phone": "1-842-317-1459",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "nunc.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Quisque Associates",
		"title": "a,",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Alan Mcguire",
		"contactFrequency": "Biweekly",
		"email": "Aenean.egestas@sapien.org",
		"phone": "1-115-926-4420",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "sed",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Interdum Industries",
		"title": "aliquet. Phasellus fermentum",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Alvin W. English",
		"contactFrequency": "Biannual",
		"email": "magna.a.tortor@arcu.co.uk",
		"phone": "1-719-757-3457",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "non,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Integer LLP",
		"title": "Nullam enim. Sed",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Veda H. Caldwell",
		"contactFrequency": "Quarterly",
		"email": "rutrum@etliberoProin.edu",
		"phone": "1-229-404-1665",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "nonummy",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "In PC",
		"title": "Aenean sed pede",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Lewis H. Conner",
		"contactFrequency": "Biweekly",
		"email": "faucibus.leo@tempusnon.com",
		"phone": "1-938-551-2377",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "consectetuer",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Vitae Velit Consulting",
		"title": "adipiscing lacus.",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Francis E. Sandoval",
		"contactFrequency": "Biweekly",
		"email": "ipsum@maurisSuspendissealiquet.edu",
		"phone": "1-557-984-8039",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "elit,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Leo Vivamus Incorporated",
		"title": "sed, sapien.",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Imogene Fitzgerald",
		"contactFrequency": "Yearly",
		"email": "purus.accumsan.interdum@dis.co.uk",
		"phone": "1-701-640-6431",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "quam",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Aliquam Corp.",
		"title": "eleifend",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Ava Shepherd",
		"contactFrequency": "Biannual",
		"email": "sed@veliteu.org",
		"phone": "1-310-928-1078",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "neque",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Proin Dolor Nulla Institute",
		"title": "amet, dapibus",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Micah K. Wooten",
		"contactFrequency": "Yearly",
		"email": "Cras.dictum@Nulla.edu",
		"phone": "1-527-222-8372",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "natoque",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Id Enim Curabitur LLP",
		"title": "erat, eget tincidunt",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Liberty U. Dotson",
		"contactFrequency": "Biannual",
		"email": "sodales.nisi.magna@Aliquamnecenim.com",
		"phone": "1-419-622-7139",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "ullamcorper.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Phasellus In Felis Company",
		"title": "aliquet",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Mannix Q. Landry",
		"contactFrequency": "Yearly",
		"email": "netus@eunequepellentesque.co.uk",
		"phone": "1-339-647-3510",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "Nunc",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut",
		"company": "Neque Non Company",
		"title": "Mauris magna. Duis",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Beatrice Y. Espinoza",
		"contactFrequency": "Yearly",
		"email": "magnis.dis.parturient@Integervulputaterisus.co.uk",
		"phone": "1-990-235-5393",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "Donec",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Fermentum Vel Ltd",
		"title": "In lorem.",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Brandon J. Mccullough",
		"contactFrequency": "Quarterly",
		"email": "Nullam@nonante.com",
		"phone": "1-647-566-8613",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "eget",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Vulputate Institute",
		"title": "erat. Etiam",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Justin Gibbs",
		"contactFrequency": "Monthly",
		"email": "et@cursus.net",
		"phone": "1-836-872-7364",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "arcu.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut",
		"company": "Montes Nascetur Limited",
		"title": "senectus",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Rooney Saunders",
		"contactFrequency": "Weekly",
		"email": "elementum.dui.quis@eunulla.ca",
		"phone": "1-295-913-7514",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "sodales",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Sagittis Felis Corp.",
		"title": "sit amet, consectetuer",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "McKenzie Fields",
		"contactFrequency": "Biweekly",
		"email": "eget.nisi@necimperdietnec.net",
		"phone": "1-171-840-5700",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "risus",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Dui Corp.",
		"title": "nec, cursus a,",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Ferdinand V. Cline",
		"contactFrequency": "Quarterly",
		"email": "condimentum@Uttincidunt.org",
		"phone": "1-349-728-0592",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "scelerisque",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Lacus Nulla Foundation",
		"title": "aliquet. Phasellus",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Akeem Thornton",
		"contactFrequency": "Weekly",
		"email": "ante@accumsan.co.uk",
		"phone": "1-581-471-0447",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "arcu.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Curabitur LLP",
		"title": "tempor",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Aspen Church",
		"contactFrequency": "Weekly",
		"email": "Sed.eget@ac.com",
		"phone": "1-319-255-8895",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "Donec",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Eu Odio Tristique Company",
		"title": "urna suscipit nonummy.",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Malachi A. Compton",
		"contactFrequency": "Yearly",
		"email": "malesuada@Sedidrisus.net",
		"phone": "1-240-787-9251",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "lacus,",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Ridiculus Mus Associates",
		"title": "augue ut",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Miriam Bowers",
		"contactFrequency": "Yearly",
		"email": "magnis.dis.parturient@Crasconvallis.org",
		"phone": "1-779-899-2196",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "Duis",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Non Lorem Vitae LLC",
		"title": "torquent per conubia",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Madaline Mack",
		"contactFrequency": "Monthly",
		"email": "a.neque.Nullam@dui.net",
		"phone": "1-514-263-1745",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "dictum",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Ut Pharetra Industries",
		"title": "tristique pharetra. Quisque",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Xander Stewart",
		"contactFrequency": "Yearly",
		"email": "ligula.Nullam.enim@Duis.org",
		"phone": "1-776-296-4551",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "magnis",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Magna Malesuada Vel Corporation",
		"title": "non magna.",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Uta H. Austin",
		"contactFrequency": "Biweekly",
		"email": "natoque.penatibus@liberoProin.net",
		"phone": "1-747-800-2124",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "tortor",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Enim Nunc Institute",
		"title": "Suspendisse",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Phelan X. Page",
		"contactFrequency": "Weekly",
		"email": "molestie.Sed.id@ligulaAenean.net",
		"phone": "1-270-370-6535",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "Integer",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Quam Corp.",
		"title": "Cum",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Jordan Reyes",
		"contactFrequency": "Yearly",
		"email": "Nunc.mauris.Morbi@Proin.org",
		"phone": "1-186-555-1768",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "lectus",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu",
		"company": "Nonummy Foundation",
		"title": "Curabitur sed",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Lana Clarke",
		"contactFrequency": "Monthly",
		"email": "Donec@nisl.net",
		"phone": "1-570-151-3571",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "tempor",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Sed Corp.",
		"title": "dolor.",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Cora Gilliam",
		"contactFrequency": "Biannual",
		"email": "sollicitudin@in.net",
		"phone": "1-927-101-5713",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "metus.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Cras PC",
		"title": "nec,",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Stacey Rivers",
		"contactFrequency": "Biannual",
		"email": "Donec.sollicitudin.adipiscing@diamDuismi.org",
		"phone": "1-937-318-3201",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "intimate",
		"contextSpace": "tortor.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Felis Orci Adipiscing Company",
		"title": "sagittis felis. Donec",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Robin Y. Guy",
		"contactFrequency": "Monthly",
		"email": "nec.quam.Curabitur@inceptoshymenaeosMauris.org",
		"phone": "1-844-105-0521",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "Curabitur",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Hymenaeos Mauris Ut LLC",
		"title": "a",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Cherokee J. Maddox",
		"contactFrequency": "Monthly",
		"email": "vel.venenatis.vel@at.org",
		"phone": "1-481-261-2332",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "pellentesque,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Interdum Nunc Limited",
		"title": "Suspendisse",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Whilemina Chase",
		"contactFrequency": "Biweekly",
		"email": "Nullam@miDuisrisus.net",
		"phone": "1-123-845-1525",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "Nulla",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Nam Associates",
		"title": "Aliquam fringilla",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Baker U. Clayton",
		"contactFrequency": "Quarterly",
		"email": "dolor.Nulla.semper@egestasligula.net",
		"phone": "1-468-220-4192",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "semper",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Tincidunt Adipiscing Corporation",
		"title": "quis",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Keaton Boyd",
		"contactFrequency": "Yearly",
		"email": "nisl.Maecenas.malesuada@nonvestibulum.edu",
		"phone": "1-855-971-4081",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "orci,",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Vulputate Ullamcorper Industries",
		"title": "euismod",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Mariko L. Harrington",
		"contactFrequency": "Biannual",
		"email": "aliquet@ligulaAliquam.net",
		"phone": "1-596-268-0436",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "varius",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Duis Gravida Praesent LLP",
		"title": "Aliquam adipiscing",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Jason J. Warner",
		"contactFrequency": "Quarterly",
		"email": "massa.Integer@Nullamenim.com",
		"phone": "1-428-832-6361",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "Fusce",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Etiam Bibendum Fermentum LLP",
		"title": "Integer sem",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Charles C. Richards",
		"contactFrequency": "Weekly",
		"email": "semper@molestie.com",
		"phone": "1-696-684-3186",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "eget,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Facilisis Vitae Company",
		"title": "nec, cursus",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Roary Miller",
		"contactFrequency": "Biannual",
		"email": "egestas.rhoncus.Proin@nibh.net",
		"phone": "1-175-951-3266",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "amet",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Amet Dapibus LLC",
		"title": "nisi",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Dane T. Dalton",
		"contactFrequency": "Biannual",
		"email": "dui.augue@justoeuarcu.com",
		"phone": "1-157-131-1844",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "sit",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Vel Est Tempor Limited",
		"title": "Donec",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Isabelle Maxwell",
		"contactFrequency": "Biweekly",
		"email": "metus.Vivamus@cursusetmagna.edu",
		"phone": "1-259-223-2070",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "Integer",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Cras Vulputate Velit LLP",
		"title": "auctor",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Minerva Serrano",
		"contactFrequency": "Biweekly",
		"email": "Phasellus.libero@diameu.co.uk",
		"phone": "1-975-733-2094",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "sem",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Fermentum Vel Corp.",
		"title": "felis eget",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Allistair E. Slater",
		"contactFrequency": "Biweekly",
		"email": "in.molestie.tortor@justofaucibus.co.uk",
		"phone": "1-932-385-6373",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "et",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Lorem Ac PC",
		"title": "nunc",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Wyatt T. Faulkner",
		"contactFrequency": "Monthly",
		"email": "urna.Ut.tincidunt@mattissemperdui.ca",
		"phone": "1-655-892-1149",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "leo,",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Amet Metus Consulting",
		"title": "tellus faucibus leo,",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Tamara Guthrie",
		"contactFrequency": "Monthly",
		"email": "quam.dignissim@fermentumfermentum.co.uk",
		"phone": "1-243-101-2854",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "vitae",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Tellus Company",
		"title": "cursus",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Angelica Schultz",
		"contactFrequency": "Quarterly",
		"email": "ut@famesacturpis.org",
		"phone": "1-634-242-2666",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "mauris,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Egestas Hendrerit Neque Industries",
		"title": "posuere at, velit.",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Basia Dorsey",
		"contactFrequency": "Biannual",
		"email": "lectus@lacusvarius.co.uk",
		"phone": "1-602-196-8575",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "mauris.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Laoreet Lectus Quis Ltd",
		"title": "malesuada",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Rama J. Webster",
		"contactFrequency": "Quarterly",
		"email": "lacinia@magnaatortor.edu",
		"phone": "1-279-755-0660",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "Sed",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Diam At Pretium Consulting",
		"title": "ligula.",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Nathan F. Chaney",
		"contactFrequency": "Biweekly",
		"email": "arcu.Vivamus@penatibus.ca",
		"phone": "1-785-193-2065",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "at,",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Curabitur Dictum Phasellus PC",
		"title": "fringilla cursus purus.",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Jack Y. Ramos",
		"contactFrequency": "Monthly",
		"email": "viverra.Maecenas@malesuadaaugueut.net",
		"phone": "1-129-305-1416",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "ipsum.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Fermentum Ltd",
		"title": "sodales",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Cassady F. Barrett",
		"contactFrequency": "Monthly",
		"email": "arcu.Nunc.mauris@elitEtiamlaoreet.com",
		"phone": "1-689-121-1650",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "a,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Phasellus LLP",
		"title": "penatibus et magnis",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Kiayada Heath",
		"contactFrequency": "Biannual",
		"email": "in.aliquet@insodaleselit.org",
		"phone": "1-450-463-2380",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "vestibulum.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Tincidunt Corporation",
		"title": "non massa",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Sean A. Hyde",
		"contactFrequency": "Biweekly",
		"email": "aliquam.eros@nonummy.org",
		"phone": "1-733-475-0815",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "gravida",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Ut Quam Vel Consulting",
		"title": "faucibus",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Timothy Randolph",
		"contactFrequency": "Biannual",
		"email": "quis@hendreritidante.co.uk",
		"phone": "1-108-167-7595",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "rutrum.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Nullam Vitae Diam PC",
		"title": "sem",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Hayley Patel",
		"contactFrequency": "Quarterly",
		"email": "Suspendisse.sagittis@Maurismolestie.co.uk",
		"phone": "1-488-348-5576",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "Duis",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Integer Sem Corp.",
		"title": "Sed",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Griffith Z. Ellison",
		"contactFrequency": "Monthly",
		"email": "lacus.Etiam@etmalesuadafames.co.uk",
		"phone": "1-559-985-6708",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "magna",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Magnis Dis Corporation",
		"title": "habitant",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Zenaida D. Schultz",
		"contactFrequency": "Yearly",
		"email": "Nam.tempor@Etiamlaoreetlibero.net",
		"phone": "1-713-658-4168",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "primis",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Risus Incorporated",
		"title": "dictum magna.",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Fletcher U. Bonner",
		"contactFrequency": "Weekly",
		"email": "Aliquam.auctor.velit@maurissagittisplacerat.org",
		"phone": "1-368-920-4370",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "nibh",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Ultrices Sit PC",
		"title": "dui",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Patience D. Harrell",
		"contactFrequency": "Monthly",
		"email": "nonummy@elitfermentumrisus.edu",
		"phone": "1-771-320-1278",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "massa",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Ridiculus Mus Consulting",
		"title": "dolor sit amet,",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Amir G. Reeves",
		"contactFrequency": "Biannual",
		"email": "nibh.lacinia@metusAliquamerat.co.uk",
		"phone": "1-947-513-6317",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "ac,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Dictum LLC",
		"title": "justo.",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Tatiana Hodges",
		"contactFrequency": "Weekly",
		"email": "odio@urnanecluctus.edu",
		"phone": "1-485-687-5936",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "sed",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Mauris Foundation",
		"title": "lacus. Nulla tincidunt,",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Amber Potter",
		"contactFrequency": "Yearly",
		"email": "non.lobortis.quis@nec.com",
		"phone": "1-526-378-3836",
		"LinkedIn": "https://linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "netus",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu",
		"company": "Ac Industries",
		"title": "habitant morbi tristique",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Iliana Byrd",
		"contactFrequency": "Biannual",
		"email": "aliquam.arcu.Aliquam@liberolacus.ca",
		"phone": "1-274-740-8738",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "nisi.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Mauris Elit Dictum Institute",
		"title": "lobortis tellus",
		"ownerEmail": "pedrocantu@gmail.com"
	},
	{
		"name": "Cruz Q. West",
		"contactFrequency": "Monthly",
		"email": "magna@luctus.org",
		"phone": "1-881-785-0867",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "Quisque",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "In LLC",
		"title": "metus. Aliquam",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Xena Roman",
		"contactFrequency": "Yearly",
		"email": "diam.eu.dolor@dolor.net",
		"phone": "1-474-740-4686",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "at,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Est Nunc LLP",
		"title": "sit amet,",
		"ownerEmail": "ramadanmustafa4@gmail.com"
	},
	{
		"name": "Quemby R. Morse",
		"contactFrequency": "Weekly",
		"email": "luctus@magnaLoremipsum.net",
		"phone": "1-395-549-2555",
		"LinkedIn": "https://linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "dignissim",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Mattis Semper Industries",
		"title": "luctus",
		"ownerEmail": "shristov22@gmail.com"
	},
	{
		"name": "Karly D. Cote",
		"contactFrequency": "Monthly",
		"email": "et@urnanecluctus.org",
		"phone": "1-239-146-2759",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "purus",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Turpis Corporation",
		"title": "feugiat nec,",
		"ownerEmail": "hjyou07@gmail.com"
	},
	{
		"name": "Ignacia Macias",
		"contactFrequency": "Quarterly",
		"email": "vitae@euismodindolor.edu",
		"phone": "1-687-982-0956",
		"LinkedIn": "https://linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "porttitor",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Iaculis Lacus Foundation",
		"title": "pharetra,",
		"ownerEmail": "hjyou07@gmail.com"
	}
]


/////  SCRIPT  //////

function randomDate(start, end) {
    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()))
}


const initialCount = db.contacts.count();

for (let i = 0; i < 100; i += 1) {

  const id = initialCount + i + 1;
  const name = mockData[i].name;
  const contactFrequency = mockData[i].contactFrequency;
  const email = mockData[i].email;
  const phone = mockData[i].phone;
  const LinkedIn = mockData[i].LinkedIn + name;
  const priority = mockData[i].priority;
  const familiarity = mockData[i].familiarity;
  const contextSpace = mockData[i].contextSpace;
  const activeStatus = mockData[i].activeStatus;
  // Generate date between 2001 and present
  const lastContactDate = randomDate(new Date(2001, 0, 1), new Date());
  const notes = mockData[i].notes;
  const company = mockData[i].company;
  // Generate date between today and 2 years from today
  const nextContactDate = randomDate(new Date(), new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 730));
  const title = mockData[i].title + `${i}`;
  const ownerEmail = mockData[i].ownerEmail;

  const contact = {
    id, 
    name, 
    contactFrequency, 
    email, 
    phone, 
    LinkedIn, 
    priority,
    familiarity,
    contextSpace,
    activeStatus,
    lastContactDate,
    notes,
    company,
    nextContactDate,
	title,
	ownerEmail,
  };

  db.contacts.insertOne(contact);
}

const count = db.contacts.count();
db.counters.update({ _id: 'contacts' }, { $set: { current: count } });

print('New contacts count:', count);
